sudo: false

language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

install:
  #- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  #- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"; mkdir ${DEPS_DIR} && cd ${DEPS_DIR}; sh ${TRAVIS_BUILD_DIR}/scripts/install_cmake.sh; PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH; fi
  
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install llvm; brew outdated gcc || brew upgrade gcc; brew outdated cmake || brew upgrade cmake;fi 
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake ..
 
script:
- make all
- ./test/LearnCMake_Test

compiler:
  - clang
  - gcc

os:
  - linux
  #- osx